version: "3.8"

services:

  app:
    build: ./app
    container_name: app
    restart: always
    expose:
      - 8000
    env_file:
      - .env
    volumes:
      - app-volume:/app
    depends_on:
      - mariadb
      - nginx
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    expose:
      - 3306
    env_file:
      - .env
    volumes:
      - dbdata-volume:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u${MARIADB_USER}", "-p${MARIADB_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - media-volume:/app/media
      - static-volume:/app/static
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  app-volume:
  dbdata-volume:
  media-volume:
  static-volume:
